// GET_ALL
GET http://localhost/proiect1/assets/php/api/posts/get_all.php HTTP/1.1

###

//GET_ONE
GET http://localhost/proiect1/assets/php/api/posts/get_one.php HTTP/1.1
Content-Type: application/json

{
    "id": "0"
}

###

// CREATE
POST http://localhost/proiect1/assets/php/api/posts/create.php HTTP/1.1
Content-Type: application/json

{
    "title": "post-1",
    "body": "body-post-1 tttttttttt"
}

###

// DELETE
DELETE http://localhost/proiect1/assets/php/api/posts/delete.php HTTP/1.1
Content-Type: application/json

{
    "id": "1"
}

###

// UPDATE
PUT http://localhost/proiect1/assets/php/api/posts/update.php HTTP/1.1
Content-Type: application/json

{
    "id": "1",
    "title": "updated-1",
    "body": "updated-body"
}